version: '3'
services:
  psql:
    image: postgres
    container_name: postgresCont
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: resources
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: resources-ktor:0.0.1
    container_name: resources-ktor
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      DB_TYPE_PROD: psql
      SQL_URL: jdbc:postgresql://psql:5432/resources
    depends_on:
      psql:
        condition: service_healthy

volumes:
  postgres_data: