ktor:
  deployment:
    port: 8081
  application:
    modules:
      - com.crowdproj.resources.app.ApplicationKt.module

jwt:
  secret: "secret"
  issuer: "Crowdproj"
  audience: "prop-users"
  realm: "resources"
  clientId: "crowdproj-resources-service"
